version: "3.8"

services:
  bot_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    restart: always

  parser_service:
    build:
      context: .
      dockerfile: Dockerfile.parser
    volumes:
      - ./parserfile/excel:/usr/src/app/parserfile/excel
    restart: always