version: "3.8"
services:
  bot_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: ["python", "bot/bot_main.py"]

  parser_service:
    build:
      context: .
      dockerfile: Dockerfile.parser
    command: ["python", "parserfile/parser_main.py"]
